[project]
name = "customer-churn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Guilherme Shibuya", email = "gyudishibuya@gmail.com" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
customer-churn = "customer_churn:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
